const $=(s,c=document)=>c.querySelector(s),$$=(s,c=document)=>[...c.querySelectorAll(s)];
let audioContext;
function sonidoOpcion(){const AudioContext=window.AudioContext||window.webkitAudioContext;if(!AudioContext)return;audioContext??=new AudioContext();const ahora=audioContext.currentTime,oscilador=audioContext.createOscillator(),ganancia=audioContext.createGain();oscilador.type='sine';oscilador.frequency.setValueAtTime(660,ahora);oscilador.frequency.exponentialRampToValueAtTime(880,ahora+.09);ganancia.gain.setValueAtTime(.0001,ahora);ganancia.gain.exponentialRampToValueAtTime(.055,ahora+.015);ganancia.gain.exponentialRampToValueAtTime(.0001,ahora+.16);oscilador.connect(ganancia).connect(audioContext.destination);oscilador.start(ahora);oscilador.stop(ahora+.17)}
document.addEventListener('click',e=>{if(e.target.closest('a,button,summary,select,input[type="submit"]'))sonidoOpcion()});
$('#menu')?.addEventListener('click',()=>{const u=$('nav ul');u.classList.toggle('abierto');$('#menu').setAttribute('aria-expanded',u.classList.contains('abierto'))});
const pagina=location.pathname.split('/').pop()||'index.html';
$$('nav a').forEach(a=>a.getAttribute('href')===pagina&&a.classList.add('activo'));
$('#anio')&&($('#anio').textContent=new Date().getFullYear());
const sug={A1:'Empiezas desde cero. Te recomendamos <b>Inglés A1 – Primeros pasos</b>.',A2:'Entiendes frases básicas. Te recomendamos <b>Inglés A2 – Básico</b>.',B1:'Te defiendes en conversaciones simples. Te recomendamos <b>Inglés B1 – Intermedio</b>.',B2:'Ya hablas con fluidez. Te recomendamos <b>Inglés B2 – Avanzado</b> o <b>Conversación</b>.'};
$$('.nivel .chip[data-n]').forEach(b=>b.addEventListener('click',()=>{$$('.nivel .chip').forEach(x=>x.classList.remove('on'));b.classList.add('on');$('#sugerencia').innerHTML=sug[b.dataset.n]+' <a href="cursos.html">Ver cursos</a>'}));
$$('.filtro .chip').forEach(b=>b.addEventListener('click',()=>{$$('.filtro .chip').forEach(x=>x.classList.remove('on'));b.classList.add('on');const f=b.dataset.f;$$('.curso').forEach(c=>c.classList.toggle('oculto',f!=='todos'&&c.dataset.tipo!==f))}));
const rutas={
 A1:{curso:'Inglés A1 – Primeros pasos',mensaje:'Cada gran conversación empieza con una primera palabra. Vas a avanzar paso a paso y celebrar cada logro.',libros:['Pearson Top Notch Fundamentals – Student Book','Pearson Top Notch Fundamentals – Workbook'],docente:'Prof. Valentina Flores',enlace:'libros.html?nivel=A1'},
 A2:{curso:'Inglés A2 – Básico',mensaje:'Ya tienes una base: ahora conviértela en confianza para hablar de tu vida, tus planes y tus sueños.',libros:['Pearson Top Notch 1 – Student Book','Pearson Top Notch 1 – Workbook'],docente:'Prof. Mateo Rojas',enlace:'libros.html?nivel=A2'},
 B1:{curso:'Inglés B1 – Intermedio',mensaje:'Tu voz en inglés ya tiene fuerza. Con práctica constante podrás expresarte con mucha más libertad.',libros:['Pearson Top Notch 2 – Student Book','Pearson Top Notch 2 – Workbook'],docente:'Prof. Camila Vargas',enlace:'libros.html?nivel=B1'},
 B2:{curso:'Inglés B2 – Avanzado',mensaje:'Estás muy cerca de la fluidez. Este nivel te ayudará a debatir, escribir y presentar tus ideas con seguridad.',libros:['Pearson Top Notch 3 – Student Book','Pearson Top Notch 3 – Workbook'],docente:'Prof. Santiago Méndez',enlace:'libros.html?nivel=B2'}
};
$$('.ruta-opciones .chip[data-ruta]').forEach(b=>b.addEventListener('click',()=>{const r=rutas[b.dataset.ruta];$$('.ruta-opciones .chip').forEach(x=>x.classList.remove('on'));b.classList.add('on');$('#rutaResultado').innerHTML=`<div class="motivacion"><strong>${r.mensaje}</strong><span>Tu ruta recomendada es ${r.curso}.</span></div><div class="ruta-detalles"><div><h4>Libros Top Notch que usarás</h4><ul>${r.libros.map(libro=>`<li>${libro}</li>`).join('')}</ul></div><div><h4>Docente asignado</h4><p class="docente">${r.docente}</p><p>Te acompañará durante todo el nivel.</p></div></div><a class="btn os" href="${r.enlace}">Ver mis libros Top Notch</a>`;document.querySelector('#rutaResultado').scrollIntoView({behavior:'smooth',block:'nearest'})}));
const nivelLibro=new URLSearchParams(location.search).get('nivel'),libroElegido=nivelLibro&&document.getElementById(`libro-${nivelLibro}`);
if(libroElegido){$$('.libro-card').forEach(card=>card.classList.toggle('oculto',card!==libroElegido));libroElegido.classList.add('seleccionado');$('#libroMensaje').textContent=`Estos son los libros Pearson Top Notch recomendados para tu nivel ${nivelLibro}. ¡Tu próxima meta empieza aquí!`;requestAnimationFrame(()=>libroElegido.scrollIntoView({behavior:'smooth',block:'center'}))}
$$('.tabs .chip[data-p]').forEach(b=>b.addEventListener('click',()=>{$$('.tabs .chip').forEach(x=>x.classList.remove('on'));b.classList.add('on');$$('.panel').forEach(p=>p.classList.toggle('on',p.id===b.dataset.p))}));
const sel=$('#curso'),meses=$('#meses');
function total(){if(!sel)return;const t=(+sel.value)*(+meses.value);$$('.tot').forEach(e=>e.textContent=t?'Bs '+t:'Bs 0')}
sel?.addEventListener('change',total);meses?.addEventListener('change',total);total();
const metodo=$('#metodo');
metodo?.addEventListener('change',()=>{$$('#qr,#efectivo').forEach(panel=>panel.classList.toggle('on',panel.id===metodo.value))});
$('#pagoForm')?.addEventListener('submit',e=>{e.preventDefault();const form=e.currentTarget;if(!form.checkValidity()){form.reportValidity();return}const importe=(+sel.value)*(+meses.value),credito=importe*.13,nombre=$('#nombre').value.trim(),correo=$('#correo').value.trim(),curso=sel.options[sel.selectedIndex].textContent,modalidad=meses.value==='2'?'bimestral':'acelerado de 3 meses',numero='PS-'+new Date().getFullYear()+'-'+String(Date.now()).slice(-6),mensaje=`Hola ${nombre}, registramos correctamente tu pago de ${curso} en el plan ${modalidad}. Total: Bs ${importe}. Crédito fiscal (13%): Bs ${credito.toFixed(2)}. Factura referencial: ${numero}.`;$('#pagoExito').classList.remove('oculto');$('#correoAviso').textContent=`La confirmación está preparada para ${correo}.`;$('#factura').classList.remove('oculto');$('#facturaNumero').textContent=numero;$('#facturaNombre').textContent=nombre;$('#facturaDocumento').textContent=$('#documento').value.trim();$('#facturaCorreo').textContent=correo;$('#facturaDepartamento').textContent=$('#departamento').value;$('#facturaTotal').textContent='Bs '+importe;$('#facturaCredito').textContent='Bs '+credito.toFixed(2);$('#enviarCorreo').href=`mailto:${encodeURIComponent(correo)}?subject=${encodeURIComponent('Confirmación de pago - Purple Sky English')}&body=${encodeURIComponent(mensaje)}`;form.classList.add('oculto');window.scrollTo({top:document.body.scrollHeight,behavior:'smooth'})});
$('#copiar')?.addEventListener('click',e=>{navigator.clipboard?.writeText($('#cuenta').textContent);e.target.textContent='¡Copiado!';setTimeout(()=>e.target.textContent='Copiar número',1800)});
$('#form')?.addEventListener('submit',e=>{e.preventDefault();let ok=true;
$$('#form [required]').forEach(c=>{const m=c.nextElementSibling,v=c.value.trim(),bad=!v||(c.type==='email'&&!/^\S+@\S+\.\S+$/.test(v));m.textContent=bad?'Revisa este campo.':'';if(bad)ok=false});
if(ok){$('#form').classList.add('oculto');$('.ok').style.display='block'}});